CREATE TABLE IF NOT EXISTS settlements (
  id SERIAL PRIMARY KEY,
  tx_id1 UUID NOT NULL,
  tx_id2 UUID NOT NULL,
  tx_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);