CREATE TABLE IF NOT EXISTS markets (
  market_id UUID PRIMARY KEY NOT NULL,
  net VARCHAR(32) NOT NULL,
  statement TEXT NOT NULL,
  is_open BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP,
  image_url VARCHAR(2048)
);