# Use the official NATS server image
FROM nats:latest

# Expose the default NATS port
EXPOSE 4222

# Expose the monitoring port
EXPOSE 8222

# Command to run the NATS server
CMD ["nats-server", "-js"]
